#ifndef SkullFourierFunc_h_included
#define SkullFourierFunc_h_included

// This file is autogenerated by WolframFourierArtCode

#include "FourierFunc.h"

class SkullFourierFunc : public FourierFuncBase
{
protected:
    virtual void initSeries() override;
};

#endif
